version: '3.8'

services:
  ipvalidation:
    build:
      context: .
      dockerfile: Dockerfile
    image: dangnt520/ipvalidation:latest
    container_name: ipvalidation
    ports:
      - "8081:8081"
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - ipvalidation-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

networks:
  ipvalidation-network:
    driver: bridge